# Generated by Django 3.0.7 on 2021-01-08 10:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210107_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.images_upload_path),
        ),
    ]
